### ISSUE TITLE
Cannot assign to global variable inside loop in draw()?

### ISSUE THREAD

**Issue by Empyreans** [py5coding/py5generator#146]
Hey guys, I really appreciate the project and was testing it out.
I have a basic setup as outlined and tried on unix and windows.
Here is my code for a strange attractor:

```
import py5

a = 0.013006706160156867
b = -1.3970590537827
c = 0.5877878956936367
d = 2.9234482660691707

x1 = 1
y1 = 1

def setup():
    py5.size(800, 800)
    py5.background(255)


def draw():
    py5.stroke(1, 125)
    for i in range(0, 1024):
        py5.point(convert_to_coord(x1), 800 - convert_to_coord(y1) - 80)
        x_new = py5.sin(a*x1)*(y1**3)+py5.sin(b*y1)
        y_new = py5.cos(c*y1)*(x1**3)+py5.cos(d*x1)
        x1 = x_new # line 19
        y1 = y_new
        

def random_val():
    return (py5.random() * 2) - 1


def convert_to_coord(val):
    return (val * 100) + (800 / 2)

py5.run_sketch()
```

and here is the error:

`UnboundLocalError: local variable 'x1' referenced before assignment` on line 19

Am I missing something?

**Comment by villares** [comment]
Welcome @Empyreans !

To reassign a global variable inside a function in Python you'll need the `global` statement. Otherwise, assignment is taken to mean a local variable is being created or modified.

Add this (usually at the start of the function):

```python
global x1, y1
```

**Comment by Empyreans** [comment]
Thank you very much!
Sorry for overlooking that simple mistake, it is not an issue with py5 and can be closed or deleted, I think.
Looking forward to using this library :)

**Comment by hx2A** [comment]
Welcome @Empyreans !

For your strange attractor code, I would like to suggest using the [`points()`](http://py5.ixora.io/reference/sketch_points.html) method instead of calling `point()` repeatedly in a loop. The performance will be much faster if you calculate all of the points at once and pass the completed array to `points()`.

Have fun!

**Comment by BaGsn** [comment]
Hi,
I have the exact same problem and adding global doesn't change anything.
Any idea why?

```
import py5

global f, min_size, max_size
global up

f = 0
min_size = 10
max_size = 10
up = True

def setup():
   py5.size(200, 200)
   py5.background(255,255,255)
   py5.rect_mode(py5.CENTER)

def draw():
   py5.background(255,255,255)

   py5.rect(py5.mouse_x, py5.mouse_y, min_size + max_size * f, min_size + max_size * f)

   if(f == 1):
      up = False
   elif(f == 0):
      up = True

   if(up):
      f += .1
   else:
      f -= .1

py5.run_sketch()
```

**Comment by hx2A** [comment]
Hi, @BaGsn !

You will need to place the global statements inside the function the global variables will be used. In your case, that would be:

```python

def draw():
    global f, min_size, max_size
    global up

    py5.background(255,255,255)

    py5.rect(py5.mouse_x, py5.mouse_y, min_size + max_size * f, min_size + max_size * f)

    if(f == 1):
        up = False
    elif(f == 0):
        up = True

    if(up):
        f += .1
    else:
        f -= .1
```

Although I notice that `min_size` and `max_size` don't need to be declared as global, because you are not modifying those values inside your `draw()` function.

In Python, the rule is that if you want to *modify* a variable inside a function that was created outside the function, you need a `global` statement. If you just want to read the variable, you don't need to do anything.

This thread is interesting in that it informs my thinking about important Python concepts that need to be carefully explained to folks learning Python.

**Comment by BaGsn** [comment]
Thanks a lot!

**Comment by hx2A** [comment]
You are welcome!

I am going to close this because it isn't a py5 bug. Thanks for opening an issue and talking to us though! Happy coding, and please come back if you get stuck again.
