### ISSUE TITLE
Binder link/button missing on py5coding.org and other issues.

### ISSUE THREAD

**Issue by villares** [py5coding/py5generator#378]
Maybe I'm wrong but I remember having two distinct options on the "rocket icon", either MyBinder or Thebe, now I tried on a few browsers and I only get the Live Code (Thebe based) option (which I messed around and could make work either, but hey, I'm clumsy). 

Is it on purpose?  (then we need to change the text that mentions the Binder option)
Or something silently wen wrong?

Maybe another issue altogether, I tried to put a notebook from the py5book repo on MyBinder and it didn't work very well (but I'm not used to it): https://mybinder.org/v2/gh/py5coding/py5book/a6759b5529ccb690728bd42a6c98018ca1e92e37?urlpath=lab%2Ftree%2Findex.ipynb

![image](https://github.com/py5coding/py5generator/assets/3694604/ffed68d0-075a-4340-b580-215c1cc12521)

Can anyone please try to reproduce these?

UPDATE: Should I have reported this at the py5book repo? If so, sorry for that :(

**Comment by hx2A** [comment]
> Maybe I'm wrong but I remember having two distinct options on the "rocket icon", either MyBinder or Thebe, now I tried on a few browsers and I only get the Live Code (Thebe based) option (which I messed around and could make work either, but hey, I'm clumsy).

The Thebe - Live Code feature was and is an experimental feature added to Jupyter Book. My experience has been it works some but not all of the time. I also recall a MyBinder option under the Rocket Icon. I don't know where it went. Over a month ago I did upgrade the Jupyter Book library used to create the website. A lot of formatting broke when I did that. Perhaps the MyBinder option disappeared at the same time.

The problem is in the html Jupyter Book creates for the website. MyBinder works fine, as you saw, you can launch MyBinder with one of the "Launch Binder" links found in the README.md files in the repos.

> I tried to put a notebook from the py5book repo on MyBinder and it didn't work very well (but I'm not used to it)

The Sketch Portal is currently broken. I don't know what the problem is. I suspect I must update the JavaScript libraries that are packaged up with py5jupyter....I hope that's it. Since that is separate from py5 I am going to work on that after the py5 release. I need to focus on one thing at a time. It should work though. I might try changing the code to use [anywidget](https://pypi.org/project/anywidget/), which I am told is a better choice for notebook widgets.

**Comment by villares** [comment]
Thanks!

**Comment by hx2A** [comment]
Here's where the Sketch Portal is:

https://discourse.jupyter.org/t/widget-problem-that-breaks-jupyter/22712

JavaScript is so frustrating.

**Comment by hx2A** [comment]
I just tried testing with JupyterLab 3.6 but that didn't fix it. Not sure what the problem is. If nobody responds to that Jupyter Discourse post, I'm going to rebuild the widget stuff using the AnyWidget library I previously mentioned. Rebuilding the widget will be easier than dealing with the ugly mess that is Jupyter Notebook extensions.

I just removed the Sketch Portal stuff from the front page of py5coding.org because having something broken like that on the front page is a bad look.

**Comment by hx2A** [comment]
The binder link is now included on the dev website under the rocketship icon for relevant pages. It was a simple config change.

I also removed Sketch Portal functionality with #390. The function is still there but you get an error message if you try to use it:

```txt
RuntimeError: The sketch_widget() functionality is broken and was removed in py5 version 0.10.0. It will be re-introduced in a future release. Sorry!
```

The reference page is also still there but has a note explaining what is going on:

http://dev.py5coding.org/reference/py5tools_sketch_portal.html
