### ISSUE TITLE
Getting two different filling results for curve_vertex

### ISSUE THREAD

**Issue by Metamorphedart** [py5coding/py5generator#45]
Hi,
I've just started using this beautiful lib instead of p5py. I've imported my experimental project's code and tried to produce the same result as p5py. I thought everything was great. Then I've noticed a big difference in the filling of the curve_vertex. Since they're both based on processing, why do they both produce different results? And how can I make them look the same? Or with another question, what makes them filled different way? 
![results](https://user-images.githubusercontent.com/92932380/138309998-b3b8e08b-8620-43b8-823d-d27c0aa82107.png)

**Comment by hx2A** [comment]
Welcome, @Metamorphedart !

In Processing, the fill color is applied to whatever is considered the "inside" of the shape. When you have a shape that overlaps itself multiple times like that, it becomes somewhat confusing or undefined what is considered the "inside". Perhaps a mathematician who studied topology would have a lot to say about this, but here we are interested in a practical application and not abstract math.

For this situation, py5 is going to give you the same results as the original Processing (Java) library because py5 is using Processing's jar files. The question becomes what is different about p5py. I would be interested to see what p5 (JavaScript) does for similar code. I don't think there is "right way" for what should be considered inside or outside, or at least, there is no formal "Processing" specification that declares what the "right way" is to do this. I would not say that what p5py is doing is "wrong" just because it happens to be different.

This doesn't help you with your problem though: your goal is to write py5 code that gets the same results. To help you, I will point out some things I've learned from studying the Processing source code.

First, bezier or quadratic curves are not any kind of special shape primitives. Processing has some formulas to calculate a series of vertex points that make up the curve. Therefore a bezier curve is converted for you into a sequence of small lines. The size of those lines are determined by methods like `curve_detail()` or `bezier_detail()` and are the reasons why they exist.

The "fill" for these shapes are made up with a set of triangles with each triangle given the fill color. The triangles themselves are determined by a tessellation algorithm. This converts the vertex points into triangles. And I think this is key to your problem. In Processing and therefore py5, that tessellation is being done differently than p5py.

My understanding of tessellation is that there are many ways to do convert a polygon into triangles and some algorithms are more efficient than others. I would suggest that you go into p5py's source code and see how it is tessellating polygons. Once you figure that out, you can then use the same algorithm to convert your curves into the same set of triangles. Then you can draw the triangles in py5. This will be a bit of work but you'll only have to do it once. Most likely you'll be combing through the code for a while until you have an aha! moment and find the piece of the library you are looking for. Good luck!

**Comment by hx2A** [comment]
I don't think Processing or py5 is analyzing these shapes as separate individual units or cells and deciding which to fill in and which to leave blank. I think it is traversing the path and connecting points to form triangles, without regard to whether or not the triangles are also overlapping another segment of the path. The library p5py might be doing something different. You'll have to check the source code to see.

**Comment by hx2A** [comment]
@Metamorphedart I stumbled onto this today and thought of your work:

https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill-rule

SVG has different rules to choose from for determining inside and outside. P5py and py5 / Processing don't provide the ability to choose but perhaps difference choices have been made for us by the implementations.

**Comment by hx2A** [comment]
I'm going to close this because there isn't anything for me to do here. Please open a new issue if I can help you with anything else.
