### ISSUE TITLE
Documentation: could py5.get_surface() be linked in the Py5Surface docs?

### ISSUE THREAD

**Issue by villares** [py5coding/py5generator#77]
The `py5.get_surface()` method used in the examples provided for the Py5Surface methods, but it is kept there with the other sketch functions: https://py5.ixora.io/reference/sketch_get_surface.html

Example:
![image](https://user-images.githubusercontent.com/3694604/165125114-1bb40e72-9102-4fa7-8e46-20e5e4921cb8.png)

Could we mention and link it in these examples and also in the "Py5Surface" page?

![image](https://user-images.githubusercontent.com/3694604/165124726-310a285c-cda3-4c3c-9f83-a19c17e90151.png)

**Comment by hx2A** [comment]
This is a good idea, the documentation for the `Py5Surface` methods should mention that much of its functionality can be provided with the newer module-level methods. The `Py5Surface` documentation was written before methods like `py5.get_surface()` existed.

This will require adding a few sentences to some text files in the [documentation directory](https://github.com/hx2A/py5generator/tree/main/py5_docs/Reference/api_en). If I provide more info for what needs to be done, would you like to make a PR for this?

**Comment by villares** [comment]
Cool! You could add your directions here or in another issue! 
I'd sure like to try my hand at the docs ar some point, but I feel like I'm going super slow lately...

**Comment by hx2A** [comment]
> Cool! You could add your directions here or in another issue! I'd sure like to try my hand at the docs ar some point, but I feel like I'm going super slow lately...

Sure, take your time with this.

First, some background on the files in the [documentation directory](https://github.com/hx2A/py5generator/tree/main/py5_docs/Reference/api_en). These files are a customized format made specifically for py5generator. The file contains separators such as `@@ description` or `@@ example` or `@@ signatures` that are used to partition the file into different sections. The contents of each section can follow its own rules. I did it this way and not a format like json or xml because both of those would involve typing a lot of extra stuff and be harder to maintain.

Note that these files are partially managed by py5generator itself. The signatures and variables sections will be edited by py5generator if it detects changes in Processing's jar file. The whole thing is designed to be easy to maintain.

The section you will be interested in is the description section. The contents of this section are [reStructuredText](https://docutils.sourceforge.io/rst.html). Someday soon I will convert everything to markdown instead, to be consistent with what's happening in py5book. This will be easier for contributors because markdown is easier to learn and learning one text syntax is easier than two.

Anyhow, here's what you will need to do. First, identify the method pairs, such as `window_title()` and `Py5Surface.set_title()`. Then for each pair, find their files:

https://github.com/hx2A/py5generator/blob/main/py5_docs/Reference/api_en/Sketch_window_title.txt

https://github.com/hx2A/py5generator/blob/main/py5_docs/Reference/api_en/Py5Surface_set_title.txt

Observe that `window_title()` references `Py5Surface.set_title()` but not the other way around.

Then you need to add a sentence to the end of the `Py5Surface.set_title()` description, like so:

``` rst
Set the Sketch window's title. This will typically appear at the window's title bar. The default window title is "Sketch".

This method provides the same functionality as :doc:`sketch_window_title`.
```

The `:doc:` bit is the reStructuredText to create a link to the other file. Observe that `sketch_window_title` is the lower-cased filename of the file you are creating the link to.

That's it! Repeat this for each pair and then make a PR.

**Comment by hx2A** [comment]
If you want to get this in the next release, try to get it done within a week or so. It's not a problem if you are busy and don't have time, you can do it later when you have the bandwidth.

**Comment by villares** [comment]
Hi @hx2A, yeah, I'm quite overwhelmed right now...

Teaching the pymunk course that started today, using py5, I was showing the documentation to the students and it dawned on me we might want to subdivide the `sketch` methods in sub-categories too.

**Comment by villares** [comment]
Now I see it is subdivided, but I didn't see it!
![image](https://user-images.githubusercontent.com/3694604/167970397-ba9ecd34-1fee-40b9-8b82-91a57918c4a3.png)

Could we have this on top of the page?

**Comment by hx2A** [comment]
I understand. I'm busy also, but it's a good kind of busy.

> Teaching the pymunk course that started today, using py5, I was showing the documentation to the students and it dawned on me we might want to subdivide the `sketch` methods in sub-categories too.

There are categories and subcategories on the Sketch reference page:

http://py5.ixora.io/reference/sketch.html

(Scroll the middle panel to see it)

**Comment by hx2A** [comment]
Ha, you saw it just as I was typing a response!

Py5Graphics and Py5Shape have categories also. Otherwise the list would be overwhelming!

**Comment by hx2A** [comment]
> Could we have this on top of the page?

Hmmm, perhaps those pages could be improved to make it more obvious that there is something important that is worth scrolling to. At a minimum it should mention this in the page's table of contents in the upper right corner.

**Comment by hx2A** [comment]
@villares I just made the updates to the Py5Surface docs. It will be in the next release.

I'm going to keep this open because I like your observation that it should be more obvious that the methods broken down by categories are at the bottom of the page. I'll take care of that when I am working on the documentation improvements.

**Comment by villares** [comment]
Another idea for cross-linking:

![image](https://user-images.githubusercontent.com/3694604/179373570-54be6298-15e1-4f18-8464-a3059597bdf0.png)

**Comment by hx2A** [comment]
Good idea. I just made this change.

I checked the analogous `get_graphics()` method and I already added a similar link to Py5Graphics.
